version: "2.1"
services:
    pocket-core-testnet0:
        image: poktnetwork/pocket-core:${ENV:-staging-latest}
        privileged: true
        command: /usr/bin/expect /home/app/.pocket/local_command.sh
        build: ../../docker
        ports:
          - 8081:8081
          - 26657:26657
        expose:
          - "8081"
          - "26657"
          - "26656"
          - "46656"
        environment:
            POCKET_CORE_KEY: e6ebcc4d40a1afc248464c5c608a587f1ffcdc8e38669e79bc7805430ac682652c24e5fa7b00adc43fb277f8232ef97c3c8a48d0622691981e73ca59587ece37
            POCKET_CORE_SEEDS: ""
        networks:
          - pocket
        volumes:
          - ./local_command.sh:/home/app/.pocket/local_command.sh
          - ./chains.json:/home/app/.pocket/config/chains.json
          - ./genesis.json:/home/app/.pocket/config/genesis.json
networks:
    pocket:
        driver: bridge
